#!/usr/bin/env bash
# load balanecer haproxy install
apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxyORIGINAL.cfg
cat >> /etc/haproxy/haproxy.cfg << EOF
    listen webapp 0.0.0.0:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 2140-web-01 54.197.44.120:80 check
    server 2140-web-02 100.25.45.225:80 check
EOF
service haproxy start
